adminapp/urls.py
from django.urls import path
from adminapp import views
from adminapp.views import block_user, unblock_user,investment_list

app_name = 'adminapp'


urlpatterns = [
    path('add_company/', views.add_company, name='add_company'),
    path('companies/', views.company_list, name='company_list'),
    path('companies/edit/<int:company_id>/', views.edit_company, name='edit_company'),
    path('companies/delete/<int:company_id>/', views.delete_company, name='delete_company'),
    path('index', views.index, name='index'),
    path('add_investment_term/', views.add_investment_term, name='add_investment_term'),
    path('investment_term_list/', views.investment_terms_list, name='investment_term_list'),
    path('terms/edit/<int:term_id>/', views.edit_investment_term, name='edit_investment_term'),
    path('terms/delete/<int:term_id>/', views.delete_investment_term, name='delete_investment_term'),
    path('investment_list/', views.investment_list, name='investment_list'),
    path('block_user/<int:user_id>/', views.block_user, name='block_user'),
    path('unblock_user/<int:user_id>/', views.unblock_user, name='unblock_user'),
    path('news/add/', views.add_news, name='add_news'),
    path('news/', views.news_list, name='news_list'),
    path('news/edit/<int:news_id>/', views.edit_news, name='edit_news'),
    path('news/delete/<int:news_id>/', views.delete_news, name='delete_news'),
    path('register/', views.register, name='register'),
    path('', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    
]

appback/urls.py
# invest/urls.py
from rest_framework.authtoken.views import obtain_auth_token
from django.urls import path
from appback.views import *

urlpatterns = [
    path('investments/', InvestmentTermList.as_view(), name='investment-term-list'),
    path('investments/<int:id>/', InvestmentTermidList.as_view(), name='investment-term-id-list'),
    path('investments/<int:investment_term_id>/companies/', InvestmentTermCompany.as_view(), name='investment-term-company'),
    path('investments/<int:investment_term_id>/companies/<int:company_id>/', InvestmentTermCompanyid.as_view(), name='investment-term-company-id'),
    path('investments/place_order/', PortfolioCreateView.as_view(), name='investment-term-company-id-place-order'),
    path('portfolio/<int:user_id>/', DisplayPortfolio.as_view(), name='portfolio-user_id'),
    path('feeds/', feedlist.as_view(), name='feed-list'),



    path('companies/', CompanyList.as_view(), name='company-list'),
    path('fococompanies/', FocoCompanyList.as_view(), name='fococompany-list'),
    path('equitycompanies/', EquityCompanyList.as_view(), name='equitycompany-list'),
    path('slots/', SlotList.as_view(), name='slot-list'),
    # path('investments/', InvestmentCreate.as_view(), name='investment-create'),
    # path('investment-summary/', InvestmentSummaryView.as_view(), name='investment_summary'),


    path('news/', NewsListCreateAPIView.as_view(), name='news-list-create'),
    path('news/<int:pk>/', NewsDetailAPIView.as_view(), name='news-detail'),
]

iquecap_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include('userapp.urls')),
    path('api/', include('appback.urls')),
    path('api/', include('payment.urls')),
    path('api/', include('Calculator.urls')),
    path('',include('adminapp.urls')),
]

adminapp/models.py
from django.db import models

# Create your models here.

appback/models.py
# models.py

from django.db import models
from django.contrib.auth.models import User
from userapp.models import *
from django.core.exceptions import ValidationError
from django.contrib.auth.hashers import make_password, check_password


class Admin(models.Model):
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=20)

    def __str__(self):
        return self.username

    
    def set_password(self, raw_password):
        self.password = make_password(raw_password)
    
    def check_password(self, raw_password):
        return check_password(raw_password, self.password)

class InvestmentTerm(models.Model):
    title = models.CharField(max_length=255)
    short_title = models.CharField(max_length=100,null=True,blank=True)
    description = models.TextField()
    minimum_investment = models.DecimalField(max_digits=10, decimal_places=2)
    duration = models.CharField(max_length=255)
    returns = models.CharField(max_length=255)
    deliverables = models.CharField(max_length=255)
    video=models.URLField(max_length=200,null=True,blank=True)

    def __str__(self):
        return self.title

class InvestmentDeliverable(models.Model):
    investment_term = models.ForeignKey(InvestmentTerm, related_name='deliverable', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    url = models.URLField(max_length=200)

    def __str__(self):
        return self.title



class Company(models.Model):
    name = models.CharField(max_length=255)
    logo = models.ImageField(upload_to='logos/')
    description = models.TextField()
    bussiness_model = models.CharField(max_length=255)
    revenue_model = models.CharField(max_length=255,null=True,blank=True)
    industry = models.CharField(max_length=255,null=True,blank=True)
    duration = models.CharField(max_length=255)
    business_stage = models.CharField(max_length=255)
    hq = models.CharField(max_length=255,null=True,blank=True)
    year_founded=models.IntegerField(null=True,blank=True)
    percentage = models.CharField(max_length=255)
    investment_term = models.ForeignKey(InvestmentTerm, related_name='companies', on_delete=models.CASCADE)
    brochureUrl=models.URLField(max_length=255,null=True,blank=True)

    def __str__(self):
        return self.name


class c_Benefits(models.Model):
    company=models.ForeignKey(Company, related_name='benefits', on_delete=models.CASCADE)
    benefits=models.CharField(max_length=255)

    def __str__(self):
        return f"{self.company}"
    
class c_fileurls(models.Model):
    company=models.ForeignKey(Company,on_delete=models.CASCADE)    
    c_f_title=models.CharField(max_length=255)
    c_f_urls=models.URLField(max_length=255)

    def __str__(self):
        return f"{self.company}"

class Slot(models.Model):
    investment_term = models.ForeignKey(InvestmentTerm, related_name='slots', on_delete=models.CASCADE)
    company = models.ForeignKey(Company, related_name='slots', on_delete=models.CASCADE)
    percentage = models.DecimalField(max_digits=5, decimal_places=2)
    fixed_amount = models.DecimalField(max_digits=10, decimal_places=2)
    filled = models.BooleanField(default=False)
    slot_type=models.CharField(max_length=255,null=True,blank=True)

    def __str__(self):
        return f"{self.company.name} - {self.percentage}% - ${self.fixed_amount}"


class eqAP(models.Model):
    investment_term = models.ForeignKey(InvestmentTerm, related_name='eqAP', on_delete=models.CASCADE)
    company = models.ForeignKey(Company, related_name='eqAP', on_delete=models.CASCADE)
    e_amount = models.IntegerField()
    e_percentage = models.IntegerField()

class Investment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    investment_term = models.ForeignKey(InvestmentTerm, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.SET_NULL, null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    paid = models.BooleanField(default=False)  # Field to mark if the investment is paid


    def __str__(self):
        return f"{self.user.name} - {self.investment_term.title}"




    
class News(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    image = models.ImageField(upload_to='news_images/', blank=True, null=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title

class feeds(models.Model):
    v_title=models.CharField(max_length=225)
    v_description=models.TextField()
    v_url=models.URLField(max_length=200,null=True,blank=True)

    def __str__(self):
        return self.v_title
    

class company_portfolio(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount=models.DecimalField(max_digits=10, decimal_places=2)
    timestamp=models.CharField(max_length=100)
    company=models.ForeignKey(Company,on_delete=models.CASCADE,null=True,blank=True)
    slot=models.ForeignKey(Slot,on_delete=models.CASCADE,null=True,blank=True)
    investment_type=models.ForeignKey(InvestmentTerm,on_delete=models.CASCADE)

adminapp/forms.py
from django import forms
from django.forms import ModelForm
from appback.models import InvestmentTerm,Company,News

class InvestmentTermForm(forms.ModelForm):
    class Meta:
        model = InvestmentTerm
        fields = ['title', 'description', 'minimum_investment', 'duration', 'returns', 'deliverables', 'term_type']


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['name', 'description', 'subscription_model', 'type', 'duration', 'percentage', 'logo', 'investment_term']

class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title', 'description', 'image']

adminapp/templates/add_news.html
{% extends 'index.html' %}
<!DOCTYPE html>
{% load static %}
{% block nav %}

<!-- partial -->
<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title" style="margin-left: 10%;"> Form elements </h3>

        </div>
        <div class="row" style="margin-left: 10%;">
            <div class="col-10 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title text-center">ADD NEWS</h4>

                        <form class="forms-sample" method="post" enctype="multipart/form-data"
                            action="{% url 'adminapp:add_news' %}">
                            {% csrf_token %}

                            <div class="form-group">
                                <label for="id_title">Title</label>
                                <input type="text" class="form-control" id="id_title" placeholder="Title" name="title" required><br>
                            </div>
                            <div class="form-group">
                                <label for="id_description">Description</label>
                                <textarea id="id_description" class="form-control" placeholder="Description" name="description"
                                    required></textarea><br>
                            </div>
                            <div class="form-group">
                                <label for="id_image">Image</label>
                                <input type="file" class="form-control" id="id_image" name="image" required><br>
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Add News</button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>

    {% endblock %}

adminapp/templates/basic-tables.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Connect Plus</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="/static/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="/static/assets/vendors/flag-icon-css/css/flag-icon.min.css">
    <link rel="stylesheet" href="/static/assets/vendors/css/vendor.bundle.base.css">

    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="/static/assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="/static/assets/images/favicon.png" />
  </head>
  <body>
    <div class="container-scroller">
      <!-- partial:../../partials/_navbar.html -->
      <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
          <a class="navbar-brand brand-logo " href="#"
            style="color: white; font-family:Georgia, 'Times New Roman', Times, serif;">IQ CAP</a>
  
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-stretch">
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
          </button>
          <div class="search-field d-none d-xl-block">
            <form class="d-flex align-items-center h-100" action="#">
              <div class="input-group">
                <div class="input-group-prepend bg-transparent">
                  <i class="input-group-text border-0 mdi mdi-magnify"></i>
                </div>
                <input type="text" class="form-control bg-transparent border-0" placeholder="Search products">
              </div>
            </form>
          </div>
          <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item nav-profile dropdown">
              <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown"
                aria-expanded="false">
                <div class="nav-profile-img">
                  <img src="/static/assets/images/faces/face25.jpg" alt="image">
                </div>
                <div class="nav-profile-text">
                  <p class="mb-1 text-black">Admin</p>
                </div>
              </a>
              <div class="dropdown-menu navbar-dropdown dropdown-menu-right p-0 border-0 font-size-sm"
                aria-labelledby="profileDropdown" data-x-placement="bottom-end">
                <div class="p-3 text-center bg-primary">
                  <img class="img-avatar img-avatar48 img-avatar-thumb"
                    src="/static/assets/images/faces/face25.jpg" alt="">
                </div>
                <div class="p-2">
                  <a class="dropdown-item py-1 d-flex align-items-center justify-content-between" href="{% url 'adminapp:logout' %}">
                    <span>Log Out</span>
                    <i class="mdi mdi-logout ml-1"></i>
                  </a>
                </div>
              </div>
            </li>
          </ul>
          <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
            data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
          </button>
        </div>
      </nav>
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:../../partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
          <ul class="nav">
            <li class="nav-item nav-category">Main</li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'adminapp:index' %}">
                <span class="icon-bg"><i class="mdi mdi-cube menu-icon"></i></span>
                <span class="menu-title">Dashboard</span>
              </a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
                <span class="icon-bg"><i class="mdi mdi-crosshairs-gps menu-icon"></i></span>
                <span class="menu-title">Forms</span>
                <i class="menu-arrow"></i>
              </a>
              <div class="collapse" id="ui-basic">
                <ul class="nav flex-column sub-menu">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'adminapp:add_company' %}">
                      <span class="icon-bg"><i class="mdi mdi-format-list-bulleted menu-icon"></i></span>
                      <span class="menu-title">Add Company</span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'adminapp:add_investment_term' %}">
                      <span class="icon-bg"><i class="mdi mdi-format-list-bulleted menu-icon"></i></span>
                      <span class="menu-title">Add Terms</span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'adminapp:add_news' %}">
                      <span class="icon-bg"><i class="mdi mdi-format-list-bulleted menu-icon"></i></span>
                      <span class="menu-title">Add News</span>
                    </a>
                  </li>
                </ul>
              </div>
            </li>
           
            <li class="nav-item">
              <a class="nav-link" data-toggle="collapse" href="#tables" aria-expanded="false" aria-controls="tables">
                <span class="icon-bg"><i class="mdi mdi-table-large menu-icon"></i></span>
                <span class="menu-title">Tables</span>
                <i class="menu-arrow"></i>
              </a>
              <div class="collapse" id="tables">
                <ul class="nav flex-column sub-menu">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'adminapp:investment_term_list' %}">
                      <span class="icon-bg"><i class="mdi mdi-format-list-bulleted menu-icon"></i></span>
                      <span class="menu-title">Terms List</span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'adminapp:company_list' %}">
                      <span class="icon-bg"><i class="mdi mdi-format-list-bulleted menu-icon"></i></span>
                      <span class="menu-title">Company List</span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'adminapp:news_list' %}">
                      <span class="icon-bg"><i class="mdi mdi-format-list-bulleted menu-icon"></i></span>
                      <span class="menu-title">News List</span>
                    </a>
                </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'adminapp:investment_list' %}">
                      <span class="icon-bg"><i class="mdi mdi-format-list-bulleted menu-icon"></i></span>
                      <span class="menu-title">Users List</span>
                    </a>
                  </li>
                  <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url 'adminapp:add_investment_term' %}">
                      <span class="icon-bg"><i class="mdi mdi-format-list-bulleted menu-icon"></i></span>
                      <span class="menu-title">Add Terms</span>
                    </a>
                  </li> -->
                </ul>
              </div>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link" href="#">
                <span class="icon-bg"><i class="mdi mdi-table-large menu-icon"></i></span>
                <span class="menu-title">Tables</span>
              </a>
            </li> -->
            
  
            <!-- <li class="nav-item">
              <a class="nav-link" data-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth">
                <span class="icon-bg"><i class="mdi mdi-lock menu-icon"></i></span>
                <span class="menu-title">User Pages</span>
                <i class="menu-arrow"></i>
              </a>
              <div class="collapse" id="auth">
                <ul class="nav flex-column sub-menu">
                  <li class="nav-item"> <a class="nav-link" href="../../pages/samples/login.html"> Login </a></li>
                  <li class="nav-item"> <a class="nav-link" href="../../pages/samples/register.html"> Register </a></li>
                </ul>
              </div>
            </li> -->              
            <li class="nav-item sidebar-user-actions">
              <div class="sidebar-user-menu">
                <a href="{% url 'adminapp:logout' %}" class="nav-link"><i class="mdi mdi-logout menu-icon"></i>
                  <span class="menu-title">Log Out</span></a>
              </div>
            </li>
          </ul>
        </nav>
        <!-- partial -->
        <div class="main-panel">
          <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title"> Basic Tables </h3>
            </div>
           
              <div class="col-lg-12 stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">INVESTMENT TERMS LIST</h4>
                    <div class="table-responsive">
                      <table class="table table-bordered table-striped">
                        <thead>
                          <tr >
                            
                            <th class="table-white" > Title </th>
                            <th class="table-white" > Description </th>
                            <th class="table-white" > Min Investment </th>
                            <th class="table-white" > Duration </th>
                            <th class="table-white" > Returns </th>
                            <th class="table-white" > Deliverables </th>
                            <th class="table-white" > Update </th>
                            <th class="table-white" > Delete </th>
                          </tr>
                        </thead>
                        <tbody>
                          {% for term in investment_terms %}
                          <tr class="table">
                            
                            <td class="table-dark" > {{term.title}} </td>
                            <td class="table-dark" > {{term.description}} </td>
                            <td class="table-dark" > {{term.minimum_investment}} </td>
                            <td class="table-dark" > {{term.duration}} </td>
                            <td class="table-dark" > {{term.returns}} </td>
                            <td class="table-dark" > {{term.deliverables}} </td>

                            <td class="table-dark"> <a href="{% url 'adminapp:edit_investment_term' term.id %}"> <button type="submit" style="max-width: 100%; height: 100%;padding:5px 15px 5px 15px; border: 1px solid black; border-radius: 3px; background-color: rgb(3, 171, 115); color: aliceblue;">Edit</button></a> </td>
                            <td class="table-dark"> <a href="{% url 'adminapp:delete_investment_term' term_id=term.id %}"> <button type="submit" style="max-width: 100%; height: 100%;padding:5px 15px 5px 15px; border: 1px solid black; border-radius: 3px; background-color: rgb(171, 3, 70); color: aliceblue;" >Delete</button></a> </td>

                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- content-wrapper ends -->
          <!-- partial:../../partials/_footer.html -->
          <!-- <footer class="footer">
            <div class="footer-inner-wraper">
              <div class="d-sm-flex justify-content-center justify-content-sm-between">
                <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2020</span>
                <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap dashboard templates</a> from Bootstrapdash.com</span>
              </div>
            </div>
          </footer> -->
          <!-- partial -->
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="/static/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="/static/assets/js/off-canvas.js"></script>
    <script src="/static/assets/js/hoverable-collapse.js"></script>
    <script src="/static/assets/js/misc.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <!-- End custom js for this page -->
  </body>
</html>

adminapp/templates/edit_news.html
{% extends 'index.html' %}
<!DOCTYPE html>
{% load static %}
{% block nav %}

<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title" style="margin-left: 10%;"> Form elements </h3>

        </div>
        <div class="row" style="margin-left: 10%;">
            <div class="col-10 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title text-center">EDIT NEWS</h4>

                        <form method="post" enctype="multipart/form-data" action="">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="id_title">Title:</label>
                                <input type="text" id="id_title"  class="form-control" name="title" value="{{ news_article.title }}"
                                    required><br>
                            </div>


                            <div class="form-group">
                                <label for="id_description">Description:</label>
                                <textarea id="id_description"  class="form-control" name="description"
                                    required>{{ news_article.description }}</textarea><br>
                            </div>

                            <div class="form-group">
                                <label for="id_image">Image:</label>
                                <input type="file" id="id_image"  class="form-control" name="image"><br>
                                {% if news_article.image %}
                                <img src="{{ news_article.image.url }}" alt="{{ news_article.title }}"><br>
                                {% endif %}
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Save Changes</button>

                            <a href="{% url 'adminapp:news_list' %}"> <button type="submit"
                                    class="btn btn-primary mr-2">Cancel</button> </a>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
    {% endblock %}

adminapp/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Connect Plus</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="/static/assets/vendors/mdi/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="/static/assets/vendors/flag-icon-css/css/flag-icon.min.css">
  <link rel="stylesheet" href="/static/assets/vendors/css/vendor.bundle.base.css">
  <!-- endinject -->
  <!-- Plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <!-- endinject -->
  <!-- Layout styles -->
  <link rel="stylesheet" href="/static/assets/css/style.css">
  <!-- End layout styles -->
  <link rel="shortcut icon" href="/static/assets/images/favicon.png" />
</head>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-center auth">
        <div class="row flex-grow">
          <div class="col-lg-4 mx-auto">
            <div class="auth-form-light text-left p-5">
              <div class="brand-logo">
                <h2 class="text-center text-black ">SIGN IN</h2>
              </div>
              <h4>Hello! login let's get started</h4>

              <form class="pt-3" method="post" action="{% url 'adminapp:login' %}">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control form-control-lg" id="username" placeholder="Username" name="username" required>
                </div>
                <div class="form-group">
                    <input type="password" class="form-control form-control-lg" id="password" placeholder="Password" name="password" required>
                </div>
                <div class="mt-3">
                    <button type="submit" class="btn btn-block btn-outline-primary btn-lg font-weight-medium auth-form-btn">LOG IN</button>
                </div>
                <div class="my-2 d-flex justify-content-between align-items-center">
                    <div class="form-check">
                        <label class="form-check-label text-muted">
                            <input type="checkbox" class="form-check-input"> Keep me signed in
                        </label>
                    </div>
                </div>
                <div class="mt-3 text-center">
                    <p class="text-black font-weight-dark">Don't have an account?</p>
                    <a class="btn btn-block btn-outline-danger btn-lg font-weight-medium auth-form-btn" href="{% url 'adminapp:register' %}">SIGN UP</a>
                </div>
            </form>
            
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="/static/assets/vendors/js/vendor.bundle.base.js"></script>
  <!-- endinject -->
  <!-- Plugin js for this page -->
  <!-- End plugin js for this page -->
  <!-- inject:js -->
  <script src="/static/assets/js/off-canvas.js"></script>
  <script src="/static/assets/js/hoverable-collapse.js"></script>
  <script src="/static/assets/js/misc.js"></script>
  <!-- endinject -->
</body>

</html>